server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:todo.db
  user: ""
  password: ""
  properties:
    charSet: UTF-8

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1}] %m%n"

    - type: file
      currentLogFilename: logs/application.log
      archivedLogFilenamePattern: logs/application-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 5
      timeZone: UTC
      threshold: INFO
